name: Deploy

on:
    push:
        branches:
            - dev
            - infra-implementation

jobs:
    terraform:
        name: Terraform Deploy
        runs-on: ubuntu-latest

        env:
            TF_TOKEN_app_terraform_io: ${{ secrets.TFC_TOKEN }}


        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.12.0

            - name: Terraform Format
              run: terraform fmt
              working-directory: iac

            - name: Terraform Init
              run: terraform init
              working-directory: iac

            - name: Terraform Plan
              run: terraform plan
              working-directory: iac

            - name: Terraform Apply
              run: terraform apply -auto-approve
              working-directory: iac

            - name: Terraform Output
              run: terraform output -json
              working-directory: iac
